[2024-03-09 17:25:20,007: INFO: main: test log]
[2024-03-09 17:29:26,425: INFO: main: test log]
[2024-03-09 17:29:44,740: INFO: main: test log 2]
[2024-03-15 16:05:02,062: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-03-15 16:05:02,063: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-15 16:05:02,063: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:05:02,064: INFO: common: created directory at: artifacts]
[2024-03-15 16:05:02,064: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 16:05:02,064: ERROR: main: __init__() got an unexpected keyword argument 'root_dir']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 14, in main
    data_ingestion_config = config.get_data_ingestion_config()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/config/configuration.py", line 23, in get_data_ingestion_config
    data_ingestion_config = DataIngestionConfig(
TypeError: __init__() got an unexpected keyword argument 'root_dir'
[2024-03-15 16:07:27,422: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-03-15 16:07:27,423: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-15 16:07:27,423: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:07:27,423: INFO: common: created directory at: artifacts]
[2024-03-15 16:07:27,423: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 16:07:27,424: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/components/data_ingestion.py", line 40, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "/home/dc/anaconda3/envs/kidney_tumor_classifier/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-03-15 16:09:13,288: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-03-15 16:09:13,289: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-15 16:09:13,289: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:09:13,289: INFO: common: created directory at: artifacts]
[2024-03-15 16:09:13,289: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 16:09:13,290: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/components/data_ingestion.py", line 40, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "/home/dc/anaconda3/envs/kidney_tumor_classifier/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-03-15 16:09:37,087: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-03-15 16:09:37,088: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-15 16:09:37,088: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:09:37,088: INFO: common: created directory at: artifacts]
[2024-03-15 16:09:37,088: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 16:09:37,089: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/components/data_ingestion.py", line 40, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "/home/dc/anaconda3/envs/kidney_tumor_classifier/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-03-15 16:10:08,633: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-03-15 16:10:08,634: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-15 16:10:08,634: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:10:08,634: INFO: common: created directory at: artifacts]
[2024-03-15 16:10:08,634: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 16:10:08,634: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1Mb1kHZD0FSa3VrV7xebCy_7VkJ7rgevf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 16:20:46,361: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1Mb1kHZD0FSa3VrV7xebCy_7VkJ7rgevf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 16:20:53,228: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<< 

x==========x]
[2024-03-18 20:42:46,107: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-18 20:42:46,118: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-18 20:42:46,119: INFO: common: created directory at: artifacts]
[2024-03-18 20:42:46,119: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-18 20:43:34,164: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-18 20:43:34,166: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-18 20:43:34,167: INFO: common: created directory at: artifacts]
[2024-03-18 20:43:34,168: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-18 20:48:46,857: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-19 19:06:20,411: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-03-19 19:06:20,413: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-19 19:06:20,414: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 19:06:20,414: INFO: common: created directory at: artifacts]
[2024-03-19 19:06:20,414: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-19 19:06:20,414: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1Mb1kHZD0FSa3VrV7xebCy_7VkJ7rgevf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-19 19:17:53,860: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-03-19 19:17:53,862: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-19 19:17:53,863: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 19:17:53,863: INFO: common: created directory at: artifacts]
[2024-03-19 19:17:53,863: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-19 19:17:53,863: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1Mb1kHZD0FSa3VrV7xebCy_7VkJ7rgevf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-19 19:27:11,075: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1Mb1kHZD0FSa3VrV7xebCy_7VkJ7rgevf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-19 19:27:17,965: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<< 

x==========x]
[2024-03-19 19:29:09,698: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-03-19 19:29:09,700: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-19 19:29:09,700: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 19:29:09,701: INFO: common: created directory at: artifacts]
[2024-03-19 19:29:09,701: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-19 19:29:09,701: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1Mb1kHZD0FSa3VrV7xebCy_7VkJ7rgevf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-19 19:38:12,223: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1Mb1kHZD0FSa3VrV7xebCy_7VkJ7rgevf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-19 19:38:20,150: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<< 

x==========x]
[2024-03-19 19:38:20,151: INFO: main: ****************]
[2024-03-19 19:38:20,151: INFO: main: >>>>>>>> stage Base Model Preparation started! <<<<<<<<]
[2024-03-19 19:38:20,152: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-19 19:38:20,153: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 19:38:20,153: INFO: common: created directory at: artifacts]
[2024-03-19 19:38:20,154: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-19 19:38:20,154: ERROR: main: name 'Path' is not defined]
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    obj.main()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/pipeline/stage_02_prepare_base_model.py", line 14, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/config/configuration.py", line 39, in get_prepare_base_model_config
    root_dir=Path(config.root_dir),
NameError: name 'Path' is not defined
[2024-03-19 19:42:38,202: INFO: main: ****************]
[2024-03-19 19:42:38,202: INFO: main: >>>>>>>> stage Base Model Preparation started! <<<<<<<<]
[2024-03-19 19:42:38,203: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-19 19:42:38,204: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 19:42:38,204: INFO: common: created directory at: artifacts]
[2024-03-19 19:42:38,204: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-19 19:42:39,848: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-19 19:42:40,026: INFO: main: >>>>>>>> stage Base Model Preparation completed! <<<<<<<

x===========x]
[2024-03-19 21:10:05,252: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-19 21:10:05,261: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 21:10:05,262: INFO: common: created directory at: artifacts]
[2024-03-19 21:10:05,262: INFO: common: created directory at: artifacts/training]
[2024-03-20 10:02:09,972: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-20 10:02:09,974: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-20 10:02:09,975: INFO: common: created directory at: artifacts]
[2024-03-20 10:02:09,975: INFO: common: created directory at: artifacts/training]
[2024-03-20 10:02:09,978: INFO: common: created directory at: artifacts/training/tmp/ckpt]
[2024-03-20 11:12:17,316: INFO: main: ****************]
[2024-03-20 11:12:17,316: INFO: main: >>>>>>>> stage Model Training started! <<<<<<<<]
[2024-03-20 11:12:17,317: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-20 11:12:17,318: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-20 11:12:17,318: INFO: common: created directory at: artifacts]
[2024-03-20 11:12:17,318: INFO: common: created directory at: artifacts/training]
[2024-03-20 11:12:17,811: ERROR: main: 'TrainingConfig' object has no attribute 'checkpoint_path']
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    obj.main()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/pipeline/stage_03_model_training.py", line 23, in main
    keras.callbacks.ModelCheckpoint(filepath=training_config.checkpoint_path),
AttributeError: 'TrainingConfig' object has no attribute 'checkpoint_path'
[2024-03-20 11:14:50,609: INFO: main: ****************]
[2024-03-20 11:14:50,610: INFO: main: >>>>>>>> stage Model Training started! <<<<<<<<]
[2024-03-20 11:14:50,611: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-20 11:14:50,612: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-20 11:14:50,612: INFO: common: created directory at: artifacts]
[2024-03-20 11:14:50,612: INFO: common: created directory at: artifacts/training]
[2024-03-20 11:14:50,612: INFO: common: created directory at: artifacts/training/tmp/ckpt]
[2024-03-20 11:14:50,612: ERROR: main: __init__() got an unexpected keyword argument 'checkpoint_path']
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    obj.main()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/pipeline/stage_03_model_training.py", line 16, in main
    training_config = config.get_training_config()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/config/configuration.py", line 65, in get_training_config
    training_config = TrainingConfig(
TypeError: __init__() got an unexpected keyword argument 'checkpoint_path'
[2024-03-20 11:16:41,416: INFO: main: ****************]
[2024-03-20 11:16:41,416: INFO: main: >>>>>>>> stage Model Training started! <<<<<<<<]
[2024-03-20 11:16:41,417: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-20 11:16:41,418: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-20 11:16:41,418: INFO: common: created directory at: artifacts]
[2024-03-20 11:16:41,418: INFO: common: created directory at: artifacts/training]
[2024-03-20 11:16:41,418: INFO: common: created directory at: artifacts/training/tmp/ckpt]
[2024-03-20 11:26:38,139: INFO: main: >>>>>>>> stage Model Training completed! <<<<<<<

x===========x]
[2024-04-26 18:15:16,200: INFO: main: **********]
[2024-04-26 18:15:16,200: INFO: main: >>>>>stage Evaluation Stage started <<<<<]
[2024-04-26 18:15:16,200: ERROR: main: get_evaluation_config() missing 1 required positional argument: 'self']
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    obj.main()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 14, in main
    eval_config = config.get_evaluation_config()
TypeError: get_evaluation_config() missing 1 required positional argument: 'self'
[2024-04-26 18:17:55,057: INFO: main: **********]
[2024-04-26 18:17:55,057: INFO: main: >>>>>stage Evaluation Stage started <<<<<]
[2024-04-26 18:17:55,058: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-04-26 18:17:55,059: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 18:17:55,059: INFO: common: created directory at: artifacts]
[2024-04-26 18:17:55,059: ERROR: main: 'ConfigurationManager' object has no attribute 'mlflow']
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    obj.main()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 14, in main
    eval_config = config.get_evaluation_config()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/config/configuration.py", line 84, in get_evaluation_config
    mlflow_uri=self.mlflow.dagshub.MLFLOW_TRACKING_URI,
AttributeError: 'ConfigurationManager' object has no attribute 'mlflow'
[2024-04-26 18:22:52,589: INFO: main: **********]
[2024-04-26 18:22:52,589: INFO: main: >>>>>stage Evaluation Stage started <<<<<]
[2024-04-26 18:22:52,591: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-04-26 18:22:52,591: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 18:22:52,592: INFO: common: yaml file: mlflow.yaml loaded successfully]
[2024-04-26 18:22:52,592: INFO: common: created directory at: artifacts]
[2024-04-26 18:22:54,266: ERROR: main: 'EvaluationConfig' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    obj.main()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 16, in main
    evaluation.evaluation()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/components/model_evaluation.py", line 40, in evaluation
    self._valid_generator()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/components/model_evaluation.py", line 20, in _valid_generator
    target_size=self.config.params_image_size[:-1],
AttributeError: 'EvaluationConfig' object has no attribute 'params_image_size'
[2024-04-26 18:26:45,746: INFO: main: **********]
[2024-04-26 18:26:45,746: INFO: main: >>>>>stage Evaluation Stage started <<<<<]
[2024-04-26 18:26:45,748: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-04-26 18:26:45,748: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 18:26:45,749: INFO: common: yaml file: mlflow.yaml loaded successfully]
[2024-04-26 18:26:45,749: INFO: common: created directory at: artifacts]
[2024-04-26 18:26:47,279: ERROR: main: 'EvaluationConfig' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    obj.main()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 16, in main
    evaluation.evaluation()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/components/model_evaluation.py", line 40, in evaluation
    self._valid_generator()
  File "/home/dc/e2e_kidney_disease_classifier/End-to-End-Kidney-Tumor-Classification/src/cnnClassifier/components/model_evaluation.py", line 20, in _valid_generator
    target_size=self.config.params_image_size[:-1],
AttributeError: 'EvaluationConfig' object has no attribute 'params_image_size'
[2024-04-26 18:34:00,183: INFO: main: **********]
[2024-04-26 18:34:00,184: INFO: main: >>>>>stage Evaluation Stage started <<<<<]
[2024-04-26 18:34:00,185: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-04-26 18:34:00,186: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 18:34:00,186: INFO: common: yaml file: mlflow.yaml loaded successfully]
[2024-04-26 18:34:00,186: INFO: common: created directory at: artifacts]
[2024-04-26 18:37:06,852: INFO: common: json file saved at: scores.json]
[2024-04-26 18:37:06,853: INFO: common: json file saved at: scores.json]
[2024-04-26 18:37:09,377: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-26 18:37:09,853: INFO: builder_impl: Assets written to: /tmp/tmps_f6jylb/model/data/model/assets]
[2024-04-26 18:38:08,546: INFO: main: >>>>>stage Evaluation Stage completed <<<<<

x==========x]
[2024-04-26 22:51:31,881: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-04-26 22:51:31,882: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-04-26 22:51:31,882: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 22:51:31,883: INFO: common: yaml file: mlflow.yaml loaded successfully]
[2024-04-26 22:51:31,883: INFO: common: created directory at: artifacts]
[2024-04-26 22:51:31,883: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-26 22:51:31,883: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1Mb1kHZD0FSa3VrV7xebCy_7VkJ7rgevf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-26 23:07:31,802: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1Mb1kHZD0FSa3VrV7xebCy_7VkJ7rgevf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-26 23:07:38,712: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<< 

x==========x]
[2024-04-26 23:16:04,608: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-04-26 23:16:04,610: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-04-26 23:16:04,610: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 23:16:04,611: INFO: common: yaml file: mlflow.yaml loaded successfully]
[2024-04-26 23:16:04,611: INFO: common: created directory at: artifacts]
[2024-04-26 23:16:04,611: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-26 23:16:04,611: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1Mb1kHZD0FSa3VrV7xebCy_7VkJ7rgevf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-26 23:16:28,699: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-04-26 23:16:28,700: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-04-26 23:16:28,701: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 23:16:28,701: INFO: common: yaml file: mlflow.yaml loaded successfully]
[2024-04-26 23:16:28,701: INFO: common: created directory at: artifacts]
[2024-04-26 23:16:28,701: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-26 23:16:28,701: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1Mb1kHZD0FSa3VrV7xebCy_7VkJ7rgevf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-26 23:38:38,210: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1Mb1kHZD0FSa3VrV7xebCy_7VkJ7rgevf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-26 23:38:45,388: INFO: stage_01_data_ingestion: >>>>>>> stage Data Ingestion Stage completed <<<<<<< 

x==========x]
[2024-04-26 23:39:04,088: INFO: stage_02_prepare_base_model: ****************]
[2024-04-26 23:39:04,088: INFO: stage_02_prepare_base_model: >>>>>>>> stage Prepare base model started! <<<<<<<<]
[2024-04-26 23:39:04,090: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-04-26 23:39:04,091: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 23:39:04,091: INFO: common: yaml file: mlflow.yaml loaded successfully]
[2024-04-26 23:39:04,091: INFO: common: created directory at: artifacts]
[2024-04-26 23:39:04,091: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-26 23:39:05,695: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-26 23:39:05,914: INFO: stage_02_prepare_base_model: >>>>>>>> stage Prepare base model completed! <<<<<<<

x===========x]
[2024-04-26 23:40:15,764: INFO: stage_03_model_training: ************************]
[2024-04-26 23:40:15,764: INFO: stage_03_model_training: >>>>>>stage Training started <<<<<<<]
[2024-04-26 23:40:15,766: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-04-26 23:40:15,766: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 23:40:15,767: INFO: common: yaml file: mlflow.yaml loaded successfully]
[2024-04-26 23:40:15,767: INFO: common: created directory at: artifacts]
[2024-04-26 23:40:15,767: INFO: common: created directory at: artifacts/training]
[2024-04-26 23:40:15,767: INFO: common: created directory at: artifacts/training/tmp/ckpt]
[2024-04-26 23:49:49,387: INFO: stage_03_model_training: >>>>>>stage Training completed <<<<<<<

x==========x]
[2024-04-26 23:49:56,097: INFO: stage_04_model_evaluation: **********]
[2024-04-26 23:49:56,097: INFO: stage_04_model_evaluation: >>>>>stage Evaluation Stage started <<<<<]
[2024-04-26 23:49:56,098: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-04-26 23:49:56,099: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-26 23:49:56,099: INFO: common: yaml file: mlflow.yaml loaded successfully]
[2024-04-26 23:49:56,099: INFO: common: created directory at: artifacts]
[2024-04-26 23:52:44,362: INFO: common: json file saved at: scores.json]
[2024-04-26 23:52:44,362: INFO: common: json file saved at: scores.json]
[2024-04-26 23:52:47,048: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-26 23:52:47,357: INFO: builder_impl: Assets written to: /tmp/tmpba3mn4oc/model/data/model/assets]
[2024-04-26 23:53:21,117: INFO: stage_04_model_evaluation: >>>>>stage Evaluation Stage completed <<<<<

x==========x]
[2024-04-27 12:26:48,641: INFO: main: **********]
[2024-04-27 12:26:48,641: INFO: main: >>>>>stage Evaluation Stage started <<<<<]
[2024-04-27 12:26:48,642: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-04-27 12:26:48,643: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 12:26:48,644: INFO: common: yaml file: mlflow.yaml loaded successfully]
[2024-04-27 12:26:48,644: INFO: common: created directory at: artifacts]
[2024-04-27 12:29:43,404: INFO: common: json file saved at: scores.json]
[2024-04-27 12:29:43,408: INFO: common: json file saved at: scores.json]
[2024-04-27 12:29:45,669: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-27 12:29:46,140: INFO: builder_impl: Assets written to: /tmp/tmp_517irsg/model/data/model/assets]
[2024-04-27 12:30:34,692: INFO: main: >>>>>stage Evaluation Stage completed <<<<<

x==========x]
[2024-04-27 12:31:06,111: INFO: main: ****************]
[2024-04-27 12:31:06,111: INFO: main: >>>>>>>> stage Base Model Preparation started! <<<<<<<<]
[2024-04-27 12:31:06,112: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-04-27 12:31:06,113: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 12:31:06,114: INFO: common: yaml file: mlflow.yaml loaded successfully]
[2024-04-27 12:31:06,114: INFO: common: created directory at: artifacts]
[2024-04-27 12:31:06,114: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-27 12:31:07,663: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-27 12:31:07,922: INFO: main: >>>>>>>> stage Base Model Preparation completed! <<<<<<<

x===========x]
[2024-04-27 12:31:07,923: INFO: main: ****************]
[2024-04-27 12:31:07,923: INFO: main: >>>>>>>> stage Model Training started! <<<<<<<<]
[2024-04-27 12:31:07,924: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-04-27 12:31:07,925: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 12:31:07,925: INFO: common: yaml file: mlflow.yaml loaded successfully]
[2024-04-27 12:31:07,925: INFO: common: created directory at: artifacts]
[2024-04-27 12:31:07,925: INFO: common: created directory at: artifacts/training]
[2024-04-27 12:31:07,925: INFO: common: created directory at: artifacts/training/tmp/ckpt]
[2024-04-27 12:40:44,490: INFO: main: >>>>>>>> stage Model Training completed! <<<<<<<

x===========x]
[2024-04-27 12:40:44,490: INFO: main: **********]
[2024-04-27 12:40:44,490: INFO: main: >>>>>stage Evaluation Stage started <<<<<]
[2024-04-27 12:40:44,492: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-04-27 12:40:44,493: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 12:40:44,493: INFO: common: yaml file: mlflow.yaml loaded successfully]
[2024-04-27 12:40:44,493: INFO: common: created directory at: artifacts]
[2024-04-27 12:43:39,307: INFO: common: json file saved at: scores.json]
[2024-04-27 12:43:39,315: INFO: common: json file saved at: scores.json]
[2024-04-27 12:43:41,986: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-27 12:43:42,349: INFO: builder_impl: Assets written to: /tmp/tmpe9ns2m5e/model/data/model/assets]
[2024-04-27 12:44:12,966: INFO: main: >>>>>stage Evaluation Stage completed <<<<<

x==========x]
[2024-04-27 12:46:26,263: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.108:8080]
[2024-04-27 12:46:26,263: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-04-27 12:46:36,416: INFO: _internal: 127.0.0.1 - - [27/Apr/2024 12:46:36] "GET / HTTP/1.1" 200 -]
[2024-04-27 12:46:59,282: INFO: _internal: 127.0.0.1 - - [27/Apr/2024 12:46:59] "POST /predict HTTP/1.1" 200 -]
[2024-04-27 12:47:27,692: INFO: _internal: 127.0.0.1 - - [27/Apr/2024 12:47:27] "POST /predict HTTP/1.1" 200 -]
